### PR TITLE
Get rid of global state in `fail` and `warn`

### PR DESCRIPTION
**Pull request by erlend-aasland**
Here's an experiment I thought of earlier today, as a step towards error handling without global state. One of the biggest pains wrt. getting rid of the `clinic` global is that `fail` depends on it too much. So here's the experiment:

- tear of the global state from `warn_or_fail`
- identify the failing tests, and amend them by supplying the line number and filename explicitly

It is a crude change, but it kind of works, and I think it might be an improvement (if polished a little bit).

Side-effects:

- some errors now generate more accurate line numbers
- most warnings (the few we have) generate less accurate line numbers (or no at all)
- cpp.py now have a cleaner error interface towards clinic (IMO)

IMO, we should just use a variety of custom exceptions, catch these during parsing, format the error message and reraise it (for either the CLI or the test suite to catch).

### CODE REVIEW

**Comment by erlend-aasland** [comment]
After the latest yak-shaving, the diff for this PR is now greatly reduced.

**Comment by erlend-aasland** [comment]
Victor had some remarks about this PR; I'll try to address them tomorrow.

**Comment by erlend-aasland** [comment]
> * it is unclear what happens if you pass `lineno` but not `filename`

Come to think of it, that is also a concern with the current code; this PR does not alter the status quo.

**Comment by vstinner** [comment]
I wrote a different approach: https://github.com/python/cpython/pull/114752

Maybe some of these changes are still relevent with my change, I didn't dig into the code yet.

**Comment by erlend-aasland** [comment]
Upstreamed as python/cpython#115510

**Pull request closed without merging**
